name: Code Quality

on:
  push:
    branches: [ main, develop, claude/* ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.11

    - name: Install dependencies
      run: uv sync --all-extras

    - name: Run ruff linter
      run: |
        uv run ruff check . --output-format=github

    - name: Check code formatting
      run: |
        uv run ruff format --check .

    - name: Check for common issues
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        uv run ruff check . --select=E9,F63,F7,F82 --output-format=github

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.11

    - name: Install dependencies
      run: uv sync --all-extras

    - name: Run safety check (optional)
      continue-on-error: true
      run: |
        uv pip install safety
        uv run safety check --json || true

  complexity:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.11

    - name: Install dependencies
      run: uv sync --all-extras

    - name: Check code complexity
      continue-on-error: true
      run: |
        uv run ruff check . --select=C901 --output-format=github
